"""Add response_time column

Revision ID: 65da8de149e8
Revises: 
Create Date: 2025-05-21 17:16:52.050957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "65da8de149e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_column("theme")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("theme", sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
