apiVersion: v1
kind: Service
metadata:
  name: api-status-maker
  labels:
    app: api-status-maker
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: api-status-maker 